// GENERATED FILE — do not edit by hand.
// Run `npm run registry` (scripts/generate-registry.mjs) to regenerate.

type archetype = {
  id: string,
  title: string,
  layer: string,
  status: string,
  version: string,
  summary: string,
  tags: array<string>,
  aliases: array<string>,
  composedOf: array<string>,
  usedBy: array<string>,
  related: array<string>,
  intent: string,
}

let all: array<archetype> = [
  {
    id: "aspect-ratio",
    title: "Aspect Ratio",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A layout primitive that constrains content to a fixed width-to-height proportion.",
    tags: ["layout", "media", "structure", "responsive"],
    aliases: ["ratio-box", "media-box"],
    composedOf: [],
    usedBy: ["card", "carousel", "avatar", "landing-page"],
    related: ["skeleton", "scroll-area", "separator"],
    intent: "An aspect-ratio box holds its content to a consistent width-to-height proportion (16:9, 1:1, 4:3) regardless of viewport size. It keeps media grids tidy and prevents layout shift by reserving the correct space before content loads.",
  },
  {
    id: "avatar",
    title: "Avatar",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A compact visual representation of a person or entity, with a graceful fallback when no image is available.",
    tags: ["identity", "media", "display", "user"],
    aliases: ["profile-picture", "user-pic", "gravatar"],
    composedOf: [],
    usedBy: ["navbar", "card", "dropdown-menu", "comment", "sidebar"],
    related: ["badge", "skeleton"],
    intent: "An avatar represents a person or entity in a small, recognizable footprint so users can identify who is associated with content or an action at a glance. It must degrade gracefully: when an image is missing or slow, it shows a meaningful fallback rather than a broken graphic.",
  },
  {
    id: "badge",
    title: "Badge",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A small label that annotates an element with a status, category, or count.",
    tags: ["status", "label", "metadata", "count", "tag"],
    aliases: ["tag", "pill", "chip", "status-badge"],
    composedOf: [],
    usedBy: ["avatar", "card", "navbar", "table", "tabs", "sidebar"],
    related: ["button", "label"],
    intent: "A badge attaches a short, high-signal annotation to another element — a status (\"Active\"), a category (\"Beta\"), or a count (unread items). It is read at a glance and never the primary focus; it enriches the thing it sits on.",
  },
  {
    id: "button",
    title: "Button",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "An interactive control that triggers an action or event when activated.",
    tags: ["action", "control", "interactive", "form", "cta"],
    aliases: ["btn", "cta"],
    composedOf: [],
    usedBy: ["input", "navbar", "card", "form", "dialog", "landing-page"],
    related: ["link", "icon-button"],
    intent: "A button lets a person trigger a single, well-defined action — submit a form, open a dialog, confirm a choice. It is the most fundamental unit of intent in an interface: the user says \"do this now.\" A button represents an action, not a destination; navigation to another location is the job of a link.",
  },
  {
    id: "checkbox",
    title: "Checkbox",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A control for toggling a single option on or off, or selecting several from a set.",
    tags: ["form", "control", "selection", "boolean"],
    aliases: ["check", "tickbox"],
    composedOf: [],
    usedBy: ["form", "field", "data-table", "dropdown-menu"],
    related: ["switch", "radio-group", "toggle"],
    intent: "A checkbox lets a person turn a single option on or off, or pick any number of options from a set. It represents a discrete boolean choice whose effect is typically applied on form submission rather than immediately.",
  },
  {
    id: "icon-button",
    title: "Icon Button",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A compact, icon-only button that triggers an action where space is tight.",
    tags: ["action", "control", "interactive", "icon", "compact"],
    aliases: ["icon-btn", "square-button"],
    composedOf: [],
    usedBy: ["toolbar", "navbar", "data-table", "dialog", "card"],
    related: ["button", "tooltip", "toggle"],
    intent: "An icon button triggers an action using a glyph alone, trading an explicit text label for compactness. It suits dense contexts — toolbars, table rows, card corners — where a full button would crowd the layout. Because it drops the visible label, it carries a strict obligation: the icon must be recognizable and the control must still expose an accessible name.",
  },
  {
    id: "kbd",
    title: "Keyboard Key",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "An inline representation of a key or key combination the user can press.",
    tags: ["display", "keyboard", "shortcut", "hint"],
    aliases: ["kbd", "keycap", "shortcut-hint", "hotkey"],
    composedOf: [],
    usedBy: ["command", "tooltip", "dropdown-menu", "menubar"],
    related: ["badge", "tooltip"],
    intent: "A keyboard-key element renders a physical key or shortcut combination inline (\"⌘K\", \"Ctrl+S\") so users can discover and recall keyboard shortcuts. It is display-only — it documents an interaction rather than performing one.",
  },
  {
    id: "label",
    title: "Label",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A short caption that names a form control and is programmatically bound to it.",
    tags: ["form", "text", "accessibility", "field"],
    aliases: ["caption", "field-label"],
    composedOf: [],
    usedBy: ["input", "checkbox", "radio-group", "select", "switch", "field", "form"],
    related: ["field", "input"],
    intent: "A label names a form control so people know what value to provide and assistive technology can announce the control correctly. Its defining property is not the text itself but the programmatic association with a control — a label that isn't bound to anything is just text.",
  },
  {
    id: "link",
    title: "Link",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A navigational control that takes the user to another location or resource.",
    tags: ["navigation", "text", "interactive", "anchor"],
    aliases: ["anchor", "hyperlink", "a"],
    composedOf: [],
    usedBy: ["navbar", "breadcrumb", "pagination", "navigation-menu", "sidebar", "footer", "sign-in"],
    related: ["button", "icon-button"],
    intent: "A link takes the user somewhere — another page, a section of the current page, or an external resource. It represents navigation, not an action: activating a link changes location, and users rightly expect to be able to open it in a new tab, copy its address, and go back. This is the defining distinction from a button, which performs an action in place.",
  },
  {
    id: "input-otp",
    title: "One-Time-Code Input",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A segmented field for entering a short verification code one character per slot.",
    tags: ["form", "field", "control", "verification", "security"],
    aliases: ["otp-input", "pin-input", "code-input", "verification-code"],
    composedOf: [],
    usedBy: ["form", "sign-in", "dialog"],
    related: ["input", "field"],
    intent: "A one-time-code input collects a short verification code (from SMS, email, or an authenticator) with one visible slot per character. The segmented layout makes the expected length obvious, eases review, and pairs naturally with auto-advance and paste of the full code.",
  },
  {
    id: "progress",
    title: "Progress",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A visual indicator of how far a task has advanced toward completion.",
    tags: ["feedback", "status", "loading", "progress"],
    aliases: ["progress-bar", "meter", "loader-bar"],
    composedOf: [],
    usedBy: ["form", "card", "dialog", "data-table", "sidebar"],
    related: ["spinner", "skeleton", "slider"],
    intent: "A progress indicator communicates that a task is underway and, when known, how much remains. It reassures the user that work is happening and sets expectations for how long they must wait.",
  },
  {
    id: "radio-group",
    title: "Radio Group",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A set of mutually exclusive options from which exactly one can be selected.",
    tags: ["form", "control", "selection", "single-choice"],
    aliases: ["radio", "radio-buttons", "option-group"],
    composedOf: ["label"],
    usedBy: ["form", "field", "settings"],
    related: ["checkbox", "select", "toggle-group", "switch"],
    intent: "A radio group presents a small set of mutually exclusive options and lets the user choose exactly one. Showing all options at once makes the full set of choices visible and comparable, which aids decisions among a few alternatives.",
  },
  {
    id: "scroll-area",
    title: "Scroll Area",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A container that scrolls overflowing content with consistent, styleable scrollbars.",
    tags: ["layout", "scroll", "container", "overflow"],
    aliases: ["scroll-container", "scrollbox"],
    composedOf: [],
    usedBy: ["dropdown-menu", "command", "sidebar", "dialog", "data-table"],
    related: ["separator", "resizable", "aspect-ratio"],
    intent: "A scroll area confines overflowing content to a bounded region with predictable, consistently-styled scrollbars across platforms. It keeps long lists, menus, and panels contained without letting the whole page scroll.",
  },
  {
    id: "separator",
    title: "Separator",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A thin divider that visually and semantically separates groups of content.",
    tags: ["layout", "divider", "structure"],
    aliases: ["divider", "rule", "hr"],
    composedOf: [],
    usedBy: ["dropdown-menu", "menubar", "card", "sidebar", "navbar", "list"],
    related: ["scroll-area", "aspect-ratio"],
    intent: "A separator divides content into distinct groups, giving structure and rhythm without adding a heavier container. It clarifies where one set of items ends and another begins.",
  },
  {
    id: "skeleton",
    title: "Skeleton",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A placeholder that mirrors the shape of content while it loads.",
    tags: ["loading", "placeholder", "feedback", "perceived-performance"],
    aliases: ["placeholder", "shimmer", "loading-placeholder"],
    composedOf: [],
    usedBy: ["card", "data-table", "list", "avatar", "dashboard"],
    related: ["spinner", "progress"],
    intent: "A skeleton stands in for content that hasn't loaded yet, echoing its eventual layout. By reserving space in the real shape, it reduces perceived wait and prevents layout shift when the content arrives.",
  },
  {
    id: "slider",
    title: "Slider",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A control for choosing a value or range by dragging a handle along a track.",
    tags: ["form", "control", "range", "input"],
    aliases: ["range", "range-slider"],
    composedOf: [],
    usedBy: ["form", "field", "settings", "data-table"],
    related: ["input", "progress", "switch"],
    intent: "A slider lets a person pick a value from a continuous or stepped range by moving a handle along a track. It suits choices where the approximate position matters more than exact typing, and where seeing the value's place within the range is useful.",
  },
  {
    id: "spinner",
    title: "Spinner",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A compact, indeterminate indicator that signals a short, ongoing wait.",
    tags: ["loading", "feedback", "indeterminate", "status"],
    aliases: ["loader", "busy-indicator", "activity-indicator"],
    composedOf: [],
    usedBy: ["button", "form", "card", "dialog", "data-table"],
    related: ["progress", "skeleton"],
    intent: "A spinner signals that something is happening and the user should wait, without claiming to know how long. It is the lightest-weight loading cue — ideal inline, inside buttons, or over a small region during a brief, unmeasured wait.",
  },
  {
    id: "switch",
    title: "Switch",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A control that toggles a single setting on or off with an immediate effect.",
    tags: ["form", "control", "toggle", "boolean", "setting"],
    aliases: ["toggle-switch", "on-off"],
    composedOf: ["label"],
    usedBy: ["form", "field", "settings", "sidebar"],
    related: ["checkbox", "toggle"],
    intent: "A switch turns a single setting on or off, taking effect immediately like a physical light switch. Its value is the instant, self-evident nature of the change — no separate submit step.",
  },
  {
    id: "input",
    title: "Text Input",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A single-line field that lets a person enter and edit a short piece of text.",
    tags: ["form", "field", "control", "interactive", "text"],
    aliases: ["textfield", "text-field", "field"],
    composedOf: [],
    usedBy: ["form", "navbar", "sign-in", "landing-page"],
    related: ["button", "textarea", "select", "checkbox"],
    intent: "A text input captures a short, free-form value from the user — a name, an email, a search query. It is the workhorse of data entry: a labelled field the user can focus, type into, correct, and submit. A good input makes its purpose, constraints, and current validity obvious at every moment.",
  },
  {
    id: "textarea",
    title: "Textarea",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A multi-line field for entering and editing longer free-form text.",
    tags: ["form", "field", "control", "text", "multiline"],
    aliases: ["multiline-input", "text-area"],
    composedOf: [],
    usedBy: ["form", "field", "dialog", "card"],
    related: ["input", "label", "field"],
    intent: "A textarea captures longer, multi-line text — a comment, description, or message. It gives the user room to write and review several lines at once, unlike the single-line input.",
  },
  {
    id: "toggle",
    title: "Toggle",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A two-state button that can be turned on or off, often used in toolbars.",
    tags: ["control", "button", "state", "toolbar"],
    aliases: ["toggle-button", "pressed-button"],
    composedOf: [],
    usedBy: ["toggle-group", "toolbar", "menubar"],
    related: ["toggle-group", "switch", "button", "checkbox"],
    intent: "A toggle is a button that stays pressed or unpressed, representing an on/off state for a formatting or view option — bold text, grid vs. list, mute. Unlike a switch (a setting) it reads as a momentary tool that happens to remember its state, which is why it lives naturally in toolbars.",
  },
  {
    id: "toggle-group",
    title: "Toggle Group",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "A set of toggles acting as a single control for single- or multi-selection.",
    tags: ["control", "toolbar", "selection", "segmented"],
    aliases: ["segmented-control", "button-group-toggle"],
    composedOf: ["toggle"],
    usedBy: ["toolbar", "menubar", "data-table"],
    related: ["toggle", "radio-group", "tabs", "button-group"],
    intent: "A toggle group binds several toggles into one control so the user can pick one option (single-select, like a segmented control) or several (multi-select, like a formatting toolbar). It communicates that the options belong together and are governed as a set.",
  },
  {
    id: "typography",
    title: "Typography",
    layer: "element",
    status: "stable",
    version: "1.0.0",
    summary: "The system of text styles — headings, body, and inline elements — that gives content hierarchy and rhythm.",
    tags: ["text", "hierarchy", "content", "foundation"],
    aliases: ["text-styles", "prose", "type-scale"],
    composedOf: [],
    usedBy: ["card", "landing-page", "dialog", "form"],
    related: ["label", "separator"],
    intent: "Typography is the shared set of text styles — headings, body copy, lists, quotes, code, and inline emphasis — that gives written content clear hierarchy and comfortable reading rhythm. It is the connective tissue of nearly every screen; consistent type is what makes an interface feel coherent.",
  },
  {
    id: "accordion",
    title: "Accordion",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A stack of headers that expand and collapse to reveal or hide sections of content.",
    tags: ["disclosure", "content", "navigation", "faq"],
    aliases: ["expander", "disclosure-group"],
    composedOf: ["collapsible", "separator"],
    usedBy: ["landing-page", "settings", "sidebar"],
    related: ["collapsible", "tabs"],
    intent: "An accordion organizes related content into collapsible sections so users can scan headers and expand only what they need. It reduces long pages to a manageable overview and is a natural fit for FAQs and grouped settings.",
  },
  {
    id: "alert",
    title: "Alert",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "An inline message that draws attention to important, contextual information.",
    tags: ["feedback", "message", "status", "inline"],
    aliases: ["callout", "banner", "notice", "inline-message"],
    composedOf: ["button", "badge"],
    usedBy: ["form", "card", "dashboard", "settings"],
    related: ["toast", "alert-dialog", "badge"],
    intent: "An alert surfaces an important message in the flow of a page — a warning, a tip, a success confirmation, or an error summary. Unlike a toast, it stays in place and in context; unlike an alert-dialog, it doesn't interrupt or block the user.",
  },
  {
    id: "alert-dialog",
    title: "Alert Dialog",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A blocking modal that interrupts to confirm a consequential or irreversible action.",
    tags: ["modal", "confirmation", "overlay", "destructive"],
    aliases: ["confirm-dialog", "confirmation-modal"],
    composedOf: ["dialog", "button"],
    usedBy: ["data-table", "settings", "form"],
    related: ["dialog", "alert", "toast"],
    intent: "An alert dialog interrupts the user to confirm an action that is consequential or hard to undo — deleting data, discarding changes, or canceling a running job. It demands an explicit decision before anything continues, making it distinct from a general-purpose dialog used for tasks and forms.",
  },
  {
    id: "breadcrumb",
    title: "Breadcrumb",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A trail showing the current location within a hierarchy and the path back to the top.",
    tags: ["navigation", "wayfinding", "hierarchy"],
    aliases: ["breadcrumbs", "path-nav"],
    composedOf: ["link", "separator", "dropdown-menu"],
    usedBy: ["dashboard", "settings", "data-table"],
    related: ["navbar", "pagination", "tabs", "sidebar"],
    intent: "A breadcrumb shows where the current page sits within a hierarchy and offers a one-click path back to any ancestor. It answers \"where am I and how do I get back,\" reinforcing structure in deep or nested products.",
  },
  {
    id: "button-group",
    title: "Button Group",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A set of related buttons joined into a single visual unit.",
    tags: ["action", "layout", "toolbar", "grouping"],
    aliases: ["btn-group", "segmented-buttons", "split-button"],
    composedOf: ["button", "dropdown-menu", "separator"],
    usedBy: ["toolbar", "data-table", "card", "dialog"],
    related: ["toggle-group", "dropdown-menu", "button"],
    intent: "A button group visually joins related buttons into one unit to signal that they belong together — a set of related actions, or a primary action paired with a menu of alternatives (a split button). It clarifies relationships and conserves space in toolbars and action areas.",
  },
  {
    id: "calendar",
    title: "Calendar",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A grid of dates for viewing a month and selecting one or more days.",
    tags: ["date", "selection", "grid", "input"],
    aliases: ["date-grid", "month-view"],
    composedOf: ["button"],
    usedBy: ["date-picker", "form", "dashboard"],
    related: ["date-picker", "popover", "input"],
    intent: "A calendar presents dates in a familiar month grid so users can orient by weekday and week, and select a day, a range, or several days. It is the visual core that a date-picker wraps in a popover, but it also stands alone for scheduling views.",
  },
  {
    id: "card",
    title: "Card",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A self-contained surface that groups related content and actions into a single unit.",
    tags: ["container", "surface", "layout", "grouping"],
    aliases: ["tile", "panel"],
    composedOf: ["typography", "button", "badge", "avatar", "aspect-ratio", "separator"],
    usedBy: ["dashboard", "landing-page", "data-table", "settings"],
    related: ["alert", "table", "sheet"],
    intent: "A card groups related content and actions about a single subject into one bounded surface, making it scannable and manipulable as a unit. Cards turn a page of disparate information into a tidy set of digestible objects, and tile naturally into grids and lists.",
  },
  {
    id: "carousel",
    title: "Carousel",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A scrollable, paged set of items revealed a few at a time with navigation controls.",
    tags: ["media", "gallery", "slider", "content"],
    aliases: ["slider", "gallery", "slideshow"],
    composedOf: ["button", "card", "aspect-ratio"],
    usedBy: ["landing-page", "dashboard"],
    related: ["tabs", "scroll-area", "pagination"],
    intent: "A carousel presents a sequence of items — images, cards, testimonials — in a horizontally scrollable track, showing a subset at a time with controls to move through them. It suits browsable, non-essential content where saving vertical space matters more than seeing everything at once.",
  },
  {
    id: "chart",
    title: "Chart",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A visual encoding of data — bars, lines, areas, and more — that reveals patterns and comparisons.",
    tags: ["data", "visualization", "analytics", "dashboard"],
    aliases: ["graph", "plot", "data-viz"],
    composedOf: ["tooltip", "legend", "card"],
    usedBy: ["dashboard", "card", "data-table"],
    related: ["data-table", "progress", "card"],
    intent: "A chart encodes data visually so people can perceive trends, comparisons, and distributions faster than reading numbers. It turns a dataset into a shape the eye can interpret, supporting decisions on dashboards and reports.",
  },
  {
    id: "collapsible",
    title: "Collapsible",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A single region that expands and collapses to show or hide its content.",
    tags: ["disclosure", "content", "progressive-disclosure"],
    aliases: ["disclosure", "expandable", "show-more"],
    composedOf: ["button"],
    usedBy: ["accordion", "sidebar", "card", "form"],
    related: ["accordion", "popover"],
    intent: "A collapsible is a single show/hide region controlled by a trigger. It defers secondary detail until the user asks for it — a \"show more\", an optional form section, an expandable row of detail — keeping the default view clean.",
  },
  {
    id: "combobox",
    title: "Combobox",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A text input paired with a filtered list of suggestions for selecting a value.",
    tags: ["form", "selection", "search", "autocomplete"],
    aliases: ["autocomplete", "typeahead", "searchable-select"],
    composedOf: ["input", "popover", "scroll-area", "badge"],
    usedBy: ["form", "field", "command", "data-table"],
    related: ["select", "command", "input", "dropdown-menu"],
    intent: "A combobox combines a text input with a dynamically filtered list, letting users either type to narrow options or browse and pick one. It scales selection to large option sets where a plain select would be unwieldy, and supports free-form entry when allowed.",
  },
  {
    id: "command",
    title: "Command Palette",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A searchable list of commands and destinations for fast, keyboard-driven navigation and action.",
    tags: ["navigation", "search", "productivity", "keyboard"],
    aliases: ["command-palette", "command-menu", "quick-search", "spotlight"],
    composedOf: ["input", "scroll-area", "dialog", "kbd", "separator"],
    usedBy: ["dashboard", "navbar"],
    related: ["combobox", "dialog", "dropdown-menu"],
    intent: "A command palette gives power users a single, keyboard-first surface to search across commands, navigation targets, and entities, then execute or jump with a keystroke. It collapses deep menus into one fast query box, usually summoned by a shortcut from anywhere in the app.",
  },
  {
    id: "context-menu",
    title: "Context Menu",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A menu of actions relevant to a specific element, opened by right-click or long-press.",
    tags: ["menu", "actions", "contextual", "overlay"],
    aliases: ["right-click-menu", "contextual-menu"],
    composedOf: ["popover", "separator", "kbd"],
    usedBy: ["data-table", "sidebar", "card"],
    related: ["dropdown-menu", "menubar", "popover"],
    intent: "A context menu offers actions specific to the element the user targeted, summoned in place by right-click (or long-press on touch). It surfaces object-specific commands exactly where the user is working, without permanently occupying screen space.",
  },
  {
    id: "data-table",
    title: "Data Table",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "An interactive table for exploring rows of structured data with sorting, filtering, and paging.",
    tags: ["data", "table", "list", "crud", "enterprise"],
    aliases: ["datagrid", "grid", "table-view"],
    composedOf: ["table", "checkbox", "input", "combobox", "pagination", "dropdown-menu", "button", "badge", "skeleton"],
    usedBy: ["dashboard", "settings"],
    related: ["table", "pagination", "chart", "card"],
    intent: "A data table lets users explore and act on collections of structured records: sort, filter, paginate, select, and trigger row actions. It extends the static table into a working surface for datasets too large to read at once, common in admin and analytics contexts.",
  },
  {
    id: "date-picker",
    title: "Date Picker",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A field that lets users enter or choose a date (or range) via typing and a calendar.",
    tags: ["form", "date", "selection", "input"],
    aliases: ["date-input", "date-field", "datetime-picker"],
    composedOf: ["input", "calendar", "popover", "button"],
    usedBy: ["form", "field", "data-table"],
    related: ["calendar", "input", "popover", "combobox"],
    intent: "A date picker helps users provide a date (or range) accurately by combining a typed field with a calendar for browsing. It balances speed for those who know the date with visual context for those who need to see the month, and it enforces valid ranges and formats.",
  },
  {
    id: "dialog",
    title: "Dialog",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A modal overlay that focuses the user on a self-contained task or piece of content.",
    tags: ["overlay", "modal", "focus", "task"],
    aliases: ["modal", "modal-dialog", "lightbox"],
    composedOf: ["button", "scroll-area", "separator"],
    usedBy: ["form", "data-table", "dashboard", "command"],
    related: ["alert-dialog", "sheet", "drawer", "popover"],
    intent: "A dialog overlays the page to give a focused, self-contained space for a task or content — a form, details, a confirmation with body content — while dimming and disabling the rest of the interface. It concentrates attention without navigating away, then returns the user exactly where they were.",
  },
  {
    id: "drawer",
    title: "Drawer",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A panel that slides in from a screen edge, often swipe-driven, for content or actions.",
    tags: ["overlay", "panel", "mobile", "gesture"],
    aliases: ["bottom-sheet", "slide-over"],
    composedOf: ["scroll-area", "button", "separator"],
    usedBy: ["navbar", "dashboard", "data-table"],
    related: ["sheet", "dialog", "sidebar", "popover"],
    intent: "A drawer slides content in from an edge of the screen — commonly the bottom on touch — keeping partial context visible and inviting gesture-driven dismissal. It suits mobile-first flows and secondary content that should feel attached to the current screen rather than replacing it.",
  },
  {
    id: "dropdown-menu",
    title: "Dropdown Menu",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A button-triggered menu of actions, revealed in a floating list.",
    tags: ["menu", "actions", "overlay", "navigation"],
    aliases: ["action-menu", "menu-button", "overflow-menu"],
    composedOf: ["popover", "separator", "kbd", "checkbox"],
    usedBy: ["navbar", "data-table", "card", "sidebar", "toolbar"],
    related: ["context-menu", "menubar", "popover", "select"],
    intent: "A dropdown menu attaches a list of actions to a button, revealing them on demand so a surface can offer many operations without clutter. It's the workhorse for \"more actions\", account menus, and overflow — an explicitly triggered, keyboard- navigable menu of commands.",
  },
  {
    id: "empty-state",
    title: "Empty State",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A placeholder shown when there is no content yet, guiding the user toward a first action.",
    tags: ["feedback", "onboarding", "guidance", "zero-data"],
    aliases: ["zero-state", "blank-slate", "no-results"],
    composedOf: ["button", "typography", "aspect-ratio"],
    usedBy: ["data-table", "dashboard", "card", "search"],
    related: ["skeleton", "alert", "card"],
    intent: "An empty state fills the void when there's no content — a new list, no search results, a cleared inbox — turning a dead end into guidance. It explains why the space is empty and points to the next useful action, so absence of data doesn't feel like a broken screen.",
  },
  {
    id: "field",
    title: "Field",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A wrapper that pairs a form control with its label, help text, and validation message.",
    tags: ["form", "control", "layout", "validation"],
    aliases: ["form-field", "form-control", "form-group"],
    composedOf: ["label", "input", "textarea", "select", "checkbox", "radio-group", "switch"],
    usedBy: ["form", "sign-in", "settings"],
    related: ["form", "label", "input"],
    intent: "A field is the connective wrapper that turns a bare control into a complete, accessible form element: label, the control itself, optional helper text, and validation feedback — all wired together. It standardizes structure, spacing, and the label/description/error associations so every control behaves consistently.",
  },
  {
    id: "footer",
    title: "Footer",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A page-closing region with secondary navigation, legal, and trust information.",
    tags: ["navigation", "layout", "wayfinding", "legal"],
    aliases: ["site-footer", "page-footer", "colophon"],
    composedOf: ["link", "separator", "logo", "input", "button"],
    usedBy: ["landing-page", "dashboard", "pricing"],
    related: ["navbar", "sidebar"],
    intent: "A footer closes the page with the content users look for at the end: secondary navigation, legal and policy links, contact and social, and trust signals. It is the conventional home for everything that doesn't belong in primary navigation but should be reliably findable, anchoring the bottom of nearly every marketing and content page.",
  },
  {
    id: "form",
    title: "Form",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A structured set of fields that collects, validates, and submits user input toward a goal.",
    tags: ["form", "input", "validation", "data-entry"],
    aliases: ["data-entry", "input-form"],
    composedOf: ["field", "input", "textarea", "select", "checkbox", "radio-group", "switch", "button", "alert"],
    usedBy: ["sign-in", "settings", "dialog", "landing-page"],
    related: ["field", "input", "dialog"],
    intent: "A form gathers structured input from a user, validates it, and submits it to accomplish a goal — signing in, creating a record, updating settings. It orchestrates fields, guidance, validation, and submission into one coherent, accessible flow, minimizing effort and error.",
  },
  {
    id: "hover-card",
    title: "Hover Card",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A rich preview surface revealed when a pointer rests on a trigger.",
    tags: ["overlay", "preview", "contextual", "hover"],
    aliases: ["preview-card", "rich-tooltip"],
    composedOf: ["popover", "avatar", "button", "typography"],
    usedBy: ["navbar", "card", "data-table"],
    related: ["tooltip", "popover", "card"],
    intent: "A hover card shows a richer preview — a person's profile, a link's summary, an item's details — when the pointer rests on a trigger. It offers a peek of related information without a click or navigation, richer than a plain tooltip but lighter than opening a page.",
  },
  {
    id: "input-group",
    title: "Input Group",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "An input combined with adjacent add-ons or controls that act as one composite control.",
    tags: ["form", "input", "layout", "control"],
    aliases: ["input-addon", "combined-input"],
    composedOf: ["input", "button", "select", "badge"],
    usedBy: ["form", "field", "navbar", "data-table"],
    related: ["input", "field", "button-group"],
    intent: "An input group binds an input with adjacent add-ons — a prefix/suffix, an icon, a unit, a select, or a button — into one composite control. It gives the value context (currency symbol, protocol, unit) or an attached action (search, copy, apply) while reading as a single, cohesive field.",
  },
  {
    id: "list",
    title: "List",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A vertical sequence of related items, each a compact row of content and actions.",
    tags: ["collection", "rows", "content", "navigation"],
    aliases: ["list-view", "item-list", "feed"],
    composedOf: ["avatar", "badge", "button", "icon-button", "separator", "checkbox"],
    usedBy: ["dashboard", "settings", "sidebar"],
    related: ["table", "data-table", "card"],
    intent: "A list presents a set of related items as a vertical stack of rows, each showing a compact summary and optional actions. It suits object-like items scanned top to bottom — messages, files, people, notifications — where a single primary attribute leads and a table's columns would be overkill.",
  },
  {
    id: "menubar",
    title: "Menubar",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A horizontal bar of top-level menus exposing an application's commands.",
    tags: ["menu", "commands", "application", "navigation"],
    aliases: ["app-menu", "menu-bar"],
    composedOf: ["dropdown-menu", "separator", "kbd"],
    usedBy: ["dashboard"],
    related: ["dropdown-menu", "navigation-menu", "context-menu"],
    intent: "A menubar presents an application's commands as a persistent horizontal row of top-level menus (File, Edit, View…), each opening a list of grouped actions. It mirrors the desktop-application menu model, giving power users a comprehensive, predictable home for commands.",
  },
  {
    id: "navbar",
    title: "Navbar",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A persistent top-level bar that anchors identity and primary navigation across a product.",
    tags: ["navigation", "header", "layout", "wayfinding"],
    aliases: ["navbar", "top-nav", "header", "app-bar"],
    composedOf: ["button", "input", "link", "logo", "dropdown-menu", "avatar"],
    usedBy: ["landing-page", "dashboard", "settings"],
    related: ["sidebar", "tabs", "breadcrumb", "footer"],
    intent: "A navbar is the primary wayfinding surface of a product. It stays present across screens to answer three questions at a glance: where am I, where can I go, and what can I do from anywhere. It anchors brand identity and the top level of the information architecture, and it hosts the handful of global actions (search, account, primary call to action) that should be reachable from every page.",
  },
  {
    id: "navigation-menu",
    title: "Navigation Menu",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A primary navigation control whose items can open rich flyout panels of links.",
    tags: ["navigation", "menu", "wayfinding", "flyout"],
    aliases: ["mega-menu", "nav-menu", "flyout-nav"],
    composedOf: ["link", "popover", "separator"],
    usedBy: ["navbar", "landing-page"],
    related: ["navbar", "menubar", "dropdown-menu", "tabs"],
    intent: "A navigation menu presents a product's primary destinations, where top-level items can reveal flyout panels grouping related links (a \"mega menu\"). It scales site navigation beyond a flat row, organizing many destinations into browsable categories while keeping the top level clean.",
  },
  {
    id: "pagination",
    title: "Pagination",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "Controls for moving through content split across multiple pages.",
    tags: ["navigation", "data", "list", "paging"],
    aliases: ["pager", "page-nav"],
    composedOf: ["button", "link", "select"],
    usedBy: ["data-table", "table", "dashboard"],
    related: ["data-table", "table", "breadcrumb"],
    intent: "Pagination breaks a long set of results into pages and gives users controls to move among them. It bounds how much loads and renders at once, and lets users orient themselves (\"page 3 of 20\") within a large collection.",
  },
  {
    id: "popover",
    title: "Popover",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A floating surface anchored to a trigger, holding contextual content or controls.",
    tags: ["overlay", "contextual", "floating", "container"],
    aliases: ["flyout", "pop-up", "floating-panel"],
    composedOf: ["button", "scroll-area"],
    usedBy: ["combobox", "select", "date-picker", "dropdown-menu", "tooltip", "hover-card", "navigation-menu"],
    related: ["tooltip", "dropdown-menu", "dialog", "hover-card"],
    intent: "A popover is a general-purpose floating surface anchored to a trigger, used to present contextual content or lightweight controls near what they relate to. It is the shared foundation many overlays build on (menus, selects, date pickers), and on its own it holds small interactive content without the weight of a modal dialog.",
  },
  {
    id: "resizable",
    title: "Resizable Panels",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "Adjacent panels separated by draggable handles that let users redistribute space.",
    tags: ["layout", "panels", "split", "workspace"],
    aliases: ["split-pane", "split-view", "resizable-panels"],
    composedOf: ["separator", "scroll-area"],
    usedBy: ["dashboard", "data-table"],
    related: ["sidebar", "scroll-area", "separator"],
    intent: "Resizable panels divide a region into two or more areas separated by draggable handles, letting users decide how to split available space — a file tree beside an editor, a list beside a detail pane. It hands layout control to the user for workspace-style interfaces where preferred proportions vary.",
  },
  {
    id: "select",
    title: "Select",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A control that opens a list for choosing one option (or several) from a defined set.",
    tags: ["form", "selection", "dropdown", "control"],
    aliases: ["dropdown", "picker", "listbox"],
    composedOf: ["popover", "scroll-area", "separator", "checkbox"],
    usedBy: ["form", "field", "data-table", "pagination"],
    related: ["combobox", "dropdown-menu", "radio-group"],
    intent: "A select lets users choose from a defined set of options by opening a list and picking one (or several). It conserves space compared to showing all options and suits sets too long for radios but not large enough to need typed filtering.",
  },
  {
    id: "sheet",
    title: "Sheet",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A panel that slides in from a screen edge for secondary content or tasks alongside the page.",
    tags: ["overlay", "panel", "side", "task"],
    aliases: ["side-panel", "slide-over", "off-canvas"],
    composedOf: ["scroll-area", "button", "separator"],
    usedBy: ["dashboard", "data-table", "settings"],
    related: ["dialog", "drawer", "sidebar", "popover"],
    intent: "A sheet slides a panel in from an edge of the screen (commonly the side) to host secondary content or a task while keeping the page context adjacent. It's roomier than a popover and less interruptive than a centered dialog — ideal for details, filters, or edit forms that relate to what's on screen.",
  },
  {
    id: "sidebar",
    title: "Sidebar",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A persistent vertical navigation region alongside the main content of an application.",
    tags: ["navigation", "layout", "application", "wayfinding"],
    aliases: ["side-nav", "nav-rail", "app-sidebar"],
    composedOf: ["link", "button", "collapsible", "avatar", "separator", "badge", "scroll-area"],
    usedBy: ["dashboard", "settings"],
    related: ["navbar", "navigation-menu", "sheet", "drawer"],
    intent: "A sidebar provides persistent, vertically-organized navigation beside an application's content, scaling to many sections and nested groups. It's the primary wayfinding surface for product/app shells where a horizontal navbar would run out of room, keeping destinations always visible or a click away.",
  },
  {
    id: "table",
    title: "Table",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A grid of rows and columns for presenting structured, comparable data.",
    tags: ["data", "table", "structure", "comparison"],
    aliases: ["data-grid-static", "grid"],
    composedOf: ["typography", "badge", "checkbox"],
    usedBy: ["data-table", "dashboard", "card"],
    related: ["data-table", "card", "chart"],
    intent: "A table arranges structured data into rows and columns so values align for easy scanning and comparison across records and attributes. It is the clearest way to present tabular information where relationships between columns matter; the interactive data-table builds on it.",
  },
  {
    id: "tabs",
    title: "Tabs",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A set of labeled sections where selecting a tab reveals its associated panel in place.",
    tags: ["navigation", "content", "sections", "in-page"],
    aliases: ["tab-group", "segmented-views"],
    composedOf: ["separator", "badge"],
    usedBy: ["dashboard", "settings", "card"],
    related: ["accordion", "toggle-group", "navigation-menu"],
    intent: "Tabs divide related content into peer sections and let users switch between them in place, showing one panel at a time. They organize a moderate amount of content without navigation or scrolling, keeping the user in the same context while they move between views of the same subject.",
  },
  {
    id: "toast",
    title: "Toast",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A brief, self-dismissing message that confirms an action or reports a background event.",
    tags: ["feedback", "notification", "transient", "status"],
    aliases: ["snackbar", "notification", "flash-message"],
    composedOf: ["button", "progress"],
    usedBy: ["dashboard", "form", "data-table"],
    related: ["alert", "alert-dialog", "badge"],
    intent: "A toast briefly surfaces a low-friction message — \"Saved\", \"Copied\", \"Upload failed\" — then dismisses itself, confirming an action or reporting a background event without interrupting the user's flow. It's ephemeral and non-blocking, the opposite of a dialog.",
  },
  {
    id: "toolbar",
    title: "Toolbar",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A grouped row of controls that act on the current view or selection.",
    tags: ["actions", "controls", "editor", "grouping"],
    aliases: ["action-bar", "command-bar", "tool-strip"],
    composedOf: ["button", "icon-button", "toggle", "toggle-group", "separator", "dropdown-menu", "input"],
    usedBy: ["data-table", "dashboard"],
    related: ["button-group", "menubar", "navbar"],
    intent: "A toolbar gathers the controls that act on the current context — a document, canvas, selection, or list — into one consistent strip. It keeps frequently used actions visible and within reach, grouped by relationship, so users can operate without hunting through menus.",
  },
  {
    id: "tooltip",
    title: "Tooltip",
    layer: "component",
    status: "stable",
    version: "1.0.0",
    summary: "A brief text label that appears on hover or focus to clarify an element.",
    tags: ["overlay", "hint", "help", "contextual"],
    aliases: ["hint", "tip"],
    composedOf: ["popover"],
    usedBy: ["button", "navbar", "sidebar", "toggle", "data-table"],
    related: ["hover-card", "popover", "kbd"],
    intent: "A tooltip shows a short, plain-text hint about an element when the user hovers or focuses it — the meaning of an icon button, a truncated label, an extra detail. It supplies supplementary clarification without permanently occupying space, and must never carry essential or interactive content.",
  },
  {
    id: "dashboard",
    title: "Dashboard",
    layer: "page",
    status: "stable",
    version: "1.0.0",
    summary: "An at-a-glance overview page that surfaces key metrics, status, and entry points to act.",
    tags: ["analytics", "overview", "application", "data"],
    aliases: ["home", "overview", "console"],
    composedOf: ["navbar", "sidebar", "breadcrumb", "toolbar", "card", "stat", "chart", "data-table", "list", "empty-state"],
    usedBy: [],
    related: ["settings", "data-table", "chart"],
    intent: "A dashboard gives users an at-a-glance understanding of the state of a system and fast paths to act on it. It answers \"how are things, and what needs my attention?\" by arranging the most important metrics, trends, and recent activity into a scannable overview, with drill-downs to the detail behind each summary.",
  },
  {
    id: "landing-page",
    title: "Landing Page",
    layer: "page",
    status: "stable",
    version: "1.0.0",
    summary: "A standalone marketing page designed to convert a focused audience toward a single primary action.",
    tags: ["marketing", "conversion", "page", "funnel"],
    aliases: ["landing", "marketing-page", "splash"],
    composedOf: ["navbar", "hero", "feature-grid", "testimonial", "pricing-table", "faq", "cta-section", "footer", "button", "input"],
    usedBy: [],
    related: ["dashboard", "pricing", "sign-in"],
    intent: "A landing page exists to move a specific audience toward one primary action — sign up, request a demo, start a trial, buy. Unlike a general home page, it is purpose-built and self-contained: every section builds the argument for that one action, and distractions that don't serve it are removed. Success is measured by conversion, so clarity and momentum matter more than exhaustiveness.",
  },
  {
    id: "pricing",
    title: "Pricing Page",
    layer: "page",
    status: "stable",
    version: "1.0.0",
    summary: "A page that presents plans and their value to help a visitor choose and convert.",
    tags: ["marketing", "conversion", "plans", "pricing"],
    aliases: ["plans", "pricing-plans"],
    composedOf: ["navbar", "card", "badge", "switch", "toggle-group", "button", "table", "accordion", "faq", "footer"],
    usedBy: [],
    related: ["landing-page", "card"],
    intent: "A pricing page helps a visitor compare plans and choose the right one, then act. It has to make value and differences legible at a glance, reduce the anxiety of committing, and guide most people toward the intended plan — all while answering the practical questions (billing period, limits, what's included) that block a decision.",
  },
  {
    id: "settings",
    title: "Settings",
    layer: "page",
    status: "stable",
    version: "1.0.0",
    summary: "A page for viewing and changing a user's or system's configuration, organized into sections.",
    tags: ["configuration", "preferences", "forms", "account"],
    aliases: ["preferences", "account-settings", "options"],
    composedOf: ["sidebar", "tabs", "navigation-menu", "form", "field", "input", "switch", "select", "radio-group", "button", "separator", "alert"],
    usedBy: [],
    related: ["dashboard", "form"],
    intent: "A settings page lets users view and adjust configuration — account, profile, notifications, billing, security — organized so a specific option is easy to find and safe to change. It groups many controls into coherent sections and makes the state of each setting, and how changes are saved, unmistakable.",
  },
  {
    id: "sign-in",
    title: "Sign In",
    layer: "page",
    status: "stable",
    version: "1.0.0",
    summary: "A focused page that authenticates a returning user with minimal friction.",
    tags: ["auth", "authentication", "form", "account", "security"],
    aliases: ["login", "log-in", "signin"],
    composedOf: ["form", "field", "input", "input-otp", "checkbox", "button", "link", "alert", "separator"],
    usedBy: [],
    related: ["form", "settings"],
    intent: "A sign-in page authenticates a returning user and gets them into the product with as little friction as possible. It is a focused, single-purpose screen: collect credentials (or start a passwordless/again-party flow), handle errors clearly, and provide the escape hatches — reset password, alternate methods, and the path to sign up.",
  },
]
